/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-07-10 19:20:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bienvenida_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SGRAC - Sistema de Gestión de Recursos Académicos Compartidos</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style/styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"app-container\">\r\n");
      out.write("        <!-- Sidebar estilo Notion -->\r\n");
      out.write("        <div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("            <!-- Header del sidebar -->\r\n");
      out.write("            <div class=\"sidebar-header\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <i class=\"fas fa-graduation-cap\"></i>\r\n");
      out.write("                    <span class=\"logo-text\">SGRAC</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"sidebar-toggle\" id=\"sidebarToggle\">\r\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Navegación -->\r\n");
      out.write("            <nav class=\"sidebar-nav\">\r\n");
      out.write("                <!-- Inicio -->\r\n");
      out.write("                <a href=\"index.jsp\" class=\"nav-item active\">\r\n");
      out.write("                    <i class=\"fas fa-home\"></i>\r\n");
      out.write("                    <span class=\"nav-text\">Inicio</span>\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sección Recursos -->\r\n");
      out.write("                <div class=\"nav-section\">\r\n");
      out.write("                    <button class=\"nav-section-header\" onclick=\"toggleSection('recursos')\">\r\n");
      out.write("                        <i class=\"fas fa-chevron-down section-arrow\" id=\"recursos-arrow\"></i>\r\n");
      out.write("                        <i class=\"fas fa-book-open\"></i>\r\n");
      out.write("                        <span class=\"nav-text\">Recursos</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"nav-subsection\" id=\"recursos-section\">\r\n");
      out.write("                        <a href=\"upload.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-upload\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Subir Material</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"my-resources.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-file-text\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Mis Recursos</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"shared.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-share-alt\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Compartidos</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sección Búsqueda -->\r\n");
      out.write("                <div class=\"nav-section\">\r\n");
      out.write("                    <button class=\"nav-section-header\" onclick=\"toggleSection('busqueda')\">\r\n");
      out.write("                        <i class=\"fas fa-chevron-right section-arrow\" id=\"busqueda-arrow\"></i>\r\n");
      out.write("                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                        <span class=\"nav-text\">Búsqueda</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"nav-subsection collapsed\" id=\"busqueda-section\">\r\n");
      out.write("                        <a href=\"search.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-search\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Buscar Material</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"filters.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-filter\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Filtros Avanzados</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sección Perfil -->\r\n");
      out.write("                <div class=\"nav-section\">\r\n");
      out.write("                    <button class=\"nav-section-header\" onclick=\"toggleSection('perfil')\">\r\n");
      out.write("                        <i class=\"fas fa-chevron-right section-arrow\" id=\"perfil-arrow\"></i>\r\n");
      out.write("                        <i class=\"fas fa-users\"></i>\r\n");
      out.write("                        <span class=\"nav-text\">Perfil</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"nav-subsection collapsed\" id=\"perfil-section\">\r\n");
      out.write("                        <a href=\"profile.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-user\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Mi Perfil</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"notifications.jsp\" class=\"nav-subitem\">\r\n");
      out.write("                            <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                            <span class=\"nav-text\">Notificaciones</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Configuración -->\r\n");
      out.write("                <a href=\"settings.jsp\" class=\"nav-item\">\r\n");
      out.write("                    <i class=\"fas fa-cog\"></i>\r\n");
      out.write("                    <span class=\"nav-text\">Configuración</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Contenido principal -->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <!-- Header -->\r\n");
      out.write("            <header class=\"main-header\">\r\n");
      out.write("                <h1>Sistema de Gestión de Recursos Académicos Compartidos</h1>\r\n");
      out.write("                <div class=\"header-actions\">\r\n");
      out.write("                    <button class=\"btn btn-outline\">\r\n");
      out.write("                        <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                        <span>Notificaciones</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-upload\"></i>\r\n");
      out.write("                        <span>Subir Material</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <!-- Contenido de bienvenida -->\r\n");
      out.write("            <main class=\"content\">\r\n");
      out.write("                <div class=\"welcome-container\">\r\n");
      out.write("                    <!-- Bienvenida principal -->\r\n");
      out.write("                    <div class=\"welcome-hero\">\r\n");
      out.write("                        <div class=\"welcome-badge\">\r\n");
      out.write("                            <i class=\"fas fa-graduation-cap\"></i>\r\n");
      out.write("                            <span>Bienvenido al SGRAC</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2>Comparte y Accede a Recursos Académicos</h2>\r\n");
      out.write("                        <p class=\"hero-description\">\r\n");
      out.write("                            Una plataforma colaborativa diseñada para estudiantes universitarios que facilita el \r\n");
      out.write("                            intercambio de materiales de estudio, promoviendo el acceso equitativo al conocimiento.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Características principales -->\r\n");
      out.write("                    <div class=\"features-grid\">\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <div class=\"feature-header\">\r\n");
      out.write("                                <i class=\"fas fa-upload feature-icon upload\"></i>\r\n");
      out.write("                                <h3>Sube y Organiza</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Carga apuntes, exámenes, ejercicios resueltos y otros materiales de estudio. \r\n");
      out.write("                                Organízalos por facultad, materia y año de cursada.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <div class=\"feature-header\">\r\n");
      out.write("                                <i class=\"fas fa-search feature-icon search\"></i>\r\n");
      out.write("                                <h3>Búsqueda Avanzada</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Encuentra rápidamente los recursos que necesitas con filtros por facultad, \r\n");
      out.write("                                materia, tipo de material y palabras clave específicas.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <div class=\"feature-header\">\r\n");
      out.write("                                <i class=\"fas fa-share-alt feature-icon share\"></i>\r\n");
      out.write("                                <h3>Colaboración</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Comparte tus materiales con la comunidad estudiantil y accede a recursos \r\n");
      out.write("                                compartidos por otros compañeros de diferentes facultades.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Información del sistema -->\r\n");
      out.write("                    <div class=\"info-card\">\r\n");
      out.write("                        <h3>¿Qué puedes hacer en SGRAC?</h3>\r\n");
      out.write("                        <div class=\"info-grid\">\r\n");
      out.write("                            <div class=\"info-section\">\r\n");
      out.write("                                <h4>Gestión de Recursos:</h4>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>Subir apuntes de clase y materiales de estudio</li>\r\n");
      out.write("                                    <li>Compartir exámenes parciales y finales</li>\r\n");
      out.write("                                    <li>Organizar ejercicios resueltos por materia</li>\r\n");
      out.write("                                    <li>Categorizar por facultad y año de cursada</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"info-section\">\r\n");
      out.write("                                <h4>Búsqueda y Acceso:</h4>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>Filtrar por facultad y materia específica</li>\r\n");
      out.write("                                    <li>Buscar por tipo de material y palabras clave</li>\r\n");
      out.write("                                    <li>Acceder a recursos compartidos por la comunidad</li>\r\n");
      out.write("                                    <li>Recibir notificaciones sobre nuevos materiales</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Call to action -->\r\n");
      out.write("                    <div class=\"cta-section\">\r\n");
      out.write("                        <h3>¿Listo para comenzar?</h3>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Únete a la comunidad de estudiantes que ya están compartiendo y \r\n");
      out.write("                            accediendo a recursos académicos.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <div class=\"cta-buttons\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-large\">\r\n");
      out.write("                                <i class=\"fas fa-upload\"></i>\r\n");
      out.write("                                <span>Subir mi primer material</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"btn btn-outline btn-large\">\r\n");
      out.write("                                <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                <span>Explorar recursos</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </main>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
